### ISSUE TITLE
.servers is not responding

### ISSUE THREAD

**Issue by KillerRoi** [cjavad/lgsm-discord#12]
Hi there, I've done everything correctly but still the bot is not responding to .servers

![image](https://user-images.githubusercontent.com/54289708/140085819-7fd68466-fc37-43b2-8f57-0e08696a9be4.png)

**Comment by KillerRoi** [comment]
![image](https://user-images.githubusercontent.com/54289708/140085921-a8f70f62-de3b-4670-8b39-e886d74d8350.png)
as you can see it is not responding at all.

"config.ini"
![image](https://user-images.githubusercontent.com/54289708/140086065-8c0b8233-57da-4e6c-9197-bbc7ab1e262b.png)

"servers.ini"
![image](https://user-images.githubusercontent.com/54289708/140086195-ff572927-3dc2-46ae-99e9-32014c75baf2.png)

"server.ini"
![image](https://user-images.githubusercontent.com/54289708/140086283-e8c4dce0-fb8f-445a-abf9-fb1d62dcd451.png)

**Comment by cjavad** [comment]
You only need to configure "server.ini" IF you are hosting the server.js file for the socket.io remote management part of it.

If you are hosting the bot on the same machine as the server, only the bot.js file is required and the "servers.ini" file is the one in question.

Try the bot with the recommend prefix $, not sure how the . affects the results.

**Comment by cjavad** [comment]
@KillerRoi The error in question occurs when the first argument in the command "gameserver1" is not found in the .ini files, and i must admit i made this code quite a while back so the approach is not that sophisticated.

Full disclosure: I am not actively maintaining this project, but if there is a bug i would not be against patching it.

**Comment by KillerRoi** [comment]
> 
> 
> @KillerRoi The error in question occurs when the first argument in the command "gameserver1" is not found in the .ini files, and i must admit i made this code quite a while back so the approach is not that sophisticated.
> 
> Full disclosure: I am not actively maintaining this project, but if there is a bug i would not be against patching it.

isn't my servers.ini configured properly?

**Comment by cjavad** [comment]
We can test that by added a console log (yes i know) on line 50.

![image](https://user-images.githubusercontent.com/22474016/140095274-9bdfcefd-de1a-4655-afa5-c649a89f81c4.png)

Add this line in servers.js, run the bot.js, and we can see what the bot sees the config as, i suspect the config is fine but the argument parsing is where it fails.

`console.log(servers);`

**Comment by KillerRoi** [comment]
> 
> 
> We can test that by added a console log (yes i know) on line 50.
> 
> ![image](https://user-images.githubusercontent.com/22474016/140095274-9bdfcefd-de1a-4655-afa5-c649a89f81c4.png)
> 
> Add this line in servers.js, run the bot.js, and we can see what the bot sees the config as, i suspect the config is fine but the argument parsing is where it fails.
> 
> `console.log(servers);`

there's only server.js not servers.js

**Comment by KillerRoi** [comment]
![image](https://user-images.githubusercontent.com/54289708/140096697-833e50de-aea6-4cba-bea1-d617307f8edb.png)
Still not working

**Comment by KillerRoi** [comment]
`/home/ubuntu/lgsm-discord/bot.js:201
    message.availableIds.push(message.member.user.id);
                                             ^

TypeError: Cannot read property 'user' of null
    at Client.client.on.message (/home/ubuntu/lgsm-discord/bot.js:201:46)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/ubuntu/lgsm-discord/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/ubuntu/lgsm-discord/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/ubuntu/lgsm-discord/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/home/ubuntu/lgsm-discord/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/home/ubuntu/lgsm-discord/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/home/ubuntu/lgsm-discord/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.socketOnData (/home/ubuntu/lgsm-discord/node_modules/ws/lib/websocket.js:875:35)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)`
    
    This is the error

**Comment by KillerRoi** [comment]
This is the error

`/home/ubuntu/lgsm-discord/bot.js:201
    message.availableIds.push(message.member.user.id);
                                             ^

TypeError: Cannot read property 'user' of null
    at Client.client.on.message (/home/ubuntu/lgsm-discord/bot.js:201:46)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/websocket/WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (/home/ubuntu/lgsm-discord/node_modules/discord.js/src/client/websocket/WebSocketShard.js:293:10)
    at WebSocket.onMessage (/home/ubuntu/lgsm-discord/node_modules/ws/lib/event-target.js:125:16)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/ubuntu/lgsm-discord/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/ubuntu/lgsm-discord/node_modules/ws/lib/receiver.js:436:14)
    at Receiver.getData (/home/ubuntu/lgsm-discord/node_modules/ws/lib/receiver.js:366:17)
    at Receiver.startLoop (/home/ubuntu/lgsm-discord/node_modules/ws/lib/receiver.js:142:22)
    at Receiver._write (/home/ubuntu/lgsm-discord/node_modules/ws/lib/receiver.js:77:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at TLSSocket.socketOnData (/home/ubuntu/lgsm-discord/node_modules/ws/lib/websocket.js:875:35)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)`

**Comment by chiburek** [comment]
You must remove all comments from the "servers.ini".

**Comment by KillerRoi** [comment]
> You must remove all comments from the "servers.ini".

Can you add me on discord KillerRoi#8552 and help me out?
